### ISSUE TITLE
[自动无缝翻页] 在firefox上，无法取消  修改 添加历史记录，修改地址/标题 这个选项

### ISSUE THREAD

**Issue by zsjsll** [XIU2/UserScript#317]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 浏览器为firefox ，每次翻页 都会把页码记录在地址栏，取消此选项"添加历史记录，修改地址/标题 " 无效

### 错误截图（可选，也可以是一些错误代码）
>

**Comment by XIU2** [comment]
关掉 `添加历史记录+修改地址/标题` 功能后无效，说明这些网站规则写死了该功能。

比如一些搜索引擎、小说、漫画这类网站，我写规则时会加上 `"history": true,` 规则来强制开启该功能。

**Comment by zsjsll** [comment]
我希望可以全部网站都不这样做，浏览器 开启后会自动打开网页，但是 这个对地址栏进行修改后，会和第一次打开的网页不符，而且最重要的是 没有地方提醒我当前是在实际的第几页，每次角标都会变成第1页

**Comment by XIU2** [comment]
如果想要所有网站，那就需要改脚本了，这就意味着你一旦更新脚本就会覆盖你的修改。

**Comment by zsjsll** [comment]
好的，谢谢！
现在就是 刷新后，页码和翻页次数就对不上了。这会让我在使用中感觉到一点不方便，如果可以显示绝对页码就好了

**Comment by zsjsll** [comment]
好的，谢谢！
现在就是 刷新后，页码和翻页次数就对不上了。这会让我在使用中感觉到一点不方便，如果可以显示绝对页码就好了

**Comment by zsjsll** [comment]
可以通过 localstorage 来进行记录么

**Comment by zsjsll** [comment]
就是 实际位于第几页 和 左下角悬浮的页码  不统一的这个问题

**Comment by XIU2** [comment]
左下角悬浮的页码上的数字，仅代表脚本翻了几页，并不能对应网页实际页码。

也就是说，你直接打开一个位于第 3 页的网页，然后开始滚动网页翻页，翻了 5 次时，左下角悬浮的页码显示为 5，而网页实际位于第 5 页。

想要实现左下角悬浮的页码显示的是网页实际页码，要麻烦的很多，我个人不需要，因此没有动力折腾。

**Comment by zsjsll** [comment]
好的，谢谢

**Comment by Sakura-Luna** [comment]
I think the search engine forced address modification should be removed. It is not meaningful to keep this starting point, and due to some possible accidental refreshes (like chrome's memory saving), the most relevant entries will be lost, at which point a search has to be done again to get the content instead simply refresh the page.
