### ISSUE TITLE
Rewrite image links in DuckDuckGo image search

### ISSUE THREAD

**Issue by eyalroz** [XIU2/UserScript#391]
### 功能需求

I'm sorry, but I don't speak Chinese, so - I'll just write what I can here...

You offer this script:
https://github.com/XIU2/UserScript/blob/master/DuckDuckGo-Enhanced.user.js
with DDG enhancements.  I would appreciate it if the script could also make sure and rewrite DDG's links to images in the image search. 

### 预期目标

Right now, they look like this:
```
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.betanews.com%2Fscreenshots%2F1057948436-1.png&f=1&nofb=1&ipt=2f03d19caa0e6d6ef92df3ee450feac968500eaa0abc07861ff3fca870a6c863&ipo=images
```
if we unescape this, we get:
```
https://external-content.duckduckgo.com/iu/?u=https://images.betanews.com/screenshots/1057948436-1.png&f=1&nofb=1&ipt=2f03d19caa0e6d6ef92df3ee450feac968500eaa0abc07861ff3fca870a6c863&ipo=images
```
which is a waste... from this we need to extract just the actual image, URL, i.e. in the example:
```
https://images.betanews.com/screenshots/1057948436-1.png
```
If you could have your script do that - it would be great. Thanks for your efforts on maintaining these scripts!

**Comment by XIU2** [comment]
I see what you mean, but DuckDuckGo is designed this way to avoid some problems, such as:
1. The header referer limit of the image source station
2. Insecurity caused by loading images of the HTTP protocol
...

You can click the image, then click (left or right mouse button) the [View File] button on the right side of the image to get the image from the source site.

![01](https://github.com/XIU2/UserScript/assets/54703944/7f02074d-4ada-4c30-a4e7-721e755edaaf)
